interface TokenInfo {
  /**
   * OAuth access token to pass to subsequent API requests
   * Required
   * Example: U1BCMDFUMDRKV1MwMXxzLFSvXdw5PHMsVLEn_MrtcyxUsw
   */
  access_token?: string;

  /**
   * Access token TTL (time-to-live) in seconds
   * Required
   * Format: int32
   * Example: 7199
   */
  expires_in?: number;

  /**
   * OAuth refresh token (if issued)
   * Example: U1BCMDFUMDRKV1MwMXxzLFL4ec6A0XMsUv9wLriecyxS_w
   */
  refresh_token?: string;

  /**
   * Refresh token TTL (time-to-live) in seconds
   * Format: int32
   * Example: 604799
   */
  refresh_token_expires_in?: number;

  /**
   * The list of space separated application permissions (OAuth scopes)
   * Required
   * Example: AccountInfo CallLog ExtensionInfo Messages SMS
   */
  scope?: string;

  /**
   * Type of the token. The only supported value is `bearer`. This value should be used when specifying access token in `Authorization` header of subsequent API requests
   * Required
   * Example: bearer
   */
  token_type?: 'bearer';

  /**
   * Token owner's identifier. Contains RingCentral user (extension) ID
   * Example: 256440016
   */
  owner_id?: string;

  /**
   * Client application instance identifier that matches the value provided by the client,
   *  or generated by the server if a client has not provided this value
   * Example: 8zXq6oaLT7WvwWITlGiA1A
   */
  endpoint_id?: string;

  /**
   * OpenID Connect ID token (if OpenID Connect flow was activated during authorization)
   */
  id_token?: string;

  /**
   * Remaining time in seconds until session expiration due to absolute timeout.
   *  Returned only if absolute session timeout is enforced
   * Format: int32
   */
  session_expires_in?: number;

  /**
   * Absolute value of session expiration time in ISO date formatted string.
   *  Returned only if absolute session timeout is enforced
   * Format: date-time
   * Example: 2023-04-01T12:00:01Z
   */
  session_expiration_time?: string;

  /**
   * OAuth session ID
   * Required
   */
  session_id?: string;

  /**
   * Nominal value of session idle timeout in seconds.
   *  Returned only if idle session timeout is enforced
   * Format: int32
   */
  session_idle_timeout?: number;
}

export default TokenInfo;
