name: Node.js

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    environment: prod
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 23.x
      - run: yarn install
      - run: yarn reset
      - run: yarn compile
      - run: yarn test
        working-directory: test
        env:
          RINGCENTRAL_SERVER_URL: ${{ secrets.RINGCENTRAL_SERVER_URL }}
          RINGCENTRAL_CLIENT_ID: ${{ secrets.RINGCENTRAL_CLIENT_ID }}
          RINGCENTRAL_CLIENT_SECRET: ${{ secrets.RINGCENTRAL_CLIENT_SECRET }}
          RINGCENTRAL_JWT_TOKEN: ${{ secrets.RINGCENTRAL_JWT_TOKEN }}
          RINGCENTRAL_SENDER: ${{ secrets.RINGCENTRAL_SENDER }}
          RINGCENTRAL_RECEIVER: ${{ secrets.RINGCENTRAL_RECEIVER }}
