# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm reset
    - run: npm compile
    - run: npm test
      environment: sandbox
      env:
        RINGCENTRAL_SERVER_URL: ${{ secrets.RINGCENTRAL_SERVER_URL }}
        RINGCENTRAL_CLIENT_ID: ${{ secrets.RINGCENTRAL_CLIENT_ID }}
        RINGCENTRAL_CLIENT_SECRET: ${{ secrets.RINGCENTRAL_CLIENT_SECRET }}
        RINGCENTRAL_USERNAME: ${{ secrets.RINGCENTRAL_USERNAME }}
        RINGCENTRAL_EXTENSION: ${{ secrets.RINGCENTRAL_EXTENSION }}
        RINGCENTRAL_PASSWORD: ${{ secrets.RINGCENTRAL_PASSWORD }}
        RINGCENTRAL_RECEIVER: ${{ secrets.RINGCENTRAL_RECEIVER }}
        RINGCENTRAL_CALLEE: ${{ secrets.RINGCENTRAL_CALLEE }}
        # to test schedule meeting for others
        RINGCENTRAL_USERNAME2: ${{ secrets.RINGCENTRAL_USERNAME2 }}
        RINGCENTRAL_EXTENSION2: ${{ secrets.RINGCENTRAL_EXTENSION2 }}
        RINGCENTRAL_PASSWORD2: ${{ secrets.RINGCENTRAL_PASSWORD2 }}
